server:
  port: 8099

spring:
  datasource:
    url: jdbc:mysql://mysql-server:3306/mydb?serverTimezone=UTC
    username: root
    password: root
    dbcp2:
      test-while-idle: true
      validalstion-query: SELECT 1