version: '3'

services:
  mysql-server:
    image: 'mysql'
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    

  rapidfeedback-server:
    build: ../
    ports:
      - 8022:8099

  